apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
    spec:
      containers:
      - image: bitnami/mongodb:latest
        name: mongo
        ports:
        - containerPort: 27017
        env:
          - name: MONGODB_INITIAL_PRIMARY_HOST
            valueFrom:
              configMapKeyRef:
                key: MONGODB_INITIAL_PRIMARY_HOST
                name: dhbw-seminarbeit-db-env
          - name: MONGODB_DATABASE
            valueFrom:
              configMapKeyRef:
                key: MONGODB_DATABASE
                name: dhbw-seminarbeit-db-env
          - name: MONGODB_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: MONGODB_PASSWORD
                name: dhbw-seminarbeit-db-env
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: MONGODB_ROOT_PASSWORD
                name: dhbw-seminarbeit-db-env
          - name: MONGODB_USERNAME
            valueFrom:
              configMapKeyRef:
                key: MONGODB_USERNAME
                name: dhbw-seminarbeit-db-env
          - name: MONGO_PORT
            valueFrom:
              configMapKeyRef:
                key: MONGO_PORT
                name: dhbw-seminarbeit-db-env
      restartPolicy: Always
      serviceAccountName: ""
